- name: Install token-transformer
  run: npm install token-transformer
  working-directory: ./tokens

- name: Run token-transformer
  run: npx token-transformer ./tokens/tokens.json ./tokens/transformed-tokens.json
  working-directory: ./tokens

- name: Commit changes
  uses: EndBug/add-and-commit@v9

  - name: Install style-dictionary
  run: npm install -D style-dictionary
  working-directory: ./tokens

- name: Run style-dictionary
  run: npx style-dictionary build
  working-directory: ./tokens
